[package]
name = "lines"
version = "0.1.0"
authors = ["Victoria Catterson <vic@cowlet.org>"]

[dependencies]
csv = "0.14"
rustc-serialize = "0.*"
la = { git = "https://github.com/xasmx/rust-la", rev = "b475844" }
gnuplot = "0.0.20"
